name: tutorial
description: Tutorial package.
version: 1.0.8
homepage: https://github.com/warlesoncandido

environment:
  sdk: '>=2.12.0 <=4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  

